### ISSUE TITLE
Error on startup in MacOS

### ISSUE THREAD

**Issue by mixpix3ls** [skontar/bash-slides#1]
Hello,

I get the following error when starting up slides:

`./slides: line 82: slide_raw_lines: bad array subscript`

**Comment by skontar** [comment]
Hi. Unfortunately, I am unable to support MacOS myself. I am also unsure that all the needed tools are available on it (tput, head, tail, sed, date, etc.).

You can try a few things:

1. What is your bash version? Please run `bash --version`.
2. Are you sure you are executing with bash? Try `bash slides`
